# Generated by Django 5.2 on 2025-05-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Remote', 'Remote'), ('Full-time', 'Full-time'), ('On-site', 'On-site')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
