# Generated by Django 5.2 on 2025-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_author_blog_slug_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='This is a default blog content.'),
        ),
    ]
