# Generated by Django 5.2 on 2025-05-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
